# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=36, null=True)),
                ('name', models.CharField(blank=True, max_length=36, null=True)),
                ('description', models.TextField()),
                ('currency', models.CharField(blank=True, default='ZAR', max_length=4, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('attendance_limit', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=36, null=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_instance', to='classbooker.Class')),
            ],
        ),
    ]
